<?php
// $Id: biblio_citeproc.install,v 1.1.2.1 2010/07/06 20:18:24 rjerome Exp $

function biblio_citeproc_requirements($phase) {
  $requirements = array();
  $t = get_t();

  if ($phase == 'install') {
    if (!module_exists('biblio')) {
      $requirements['biblio_crossref'] = array(
        'title' => $t('Biblio'),
        'description' => $t('The Biblio module must be installed first'),
        'severity' => REQUIREMENT_ERROR
      );
    }
  }

  return $requirements;
}

